export const alumniData = [
    {
        id: 1,
        name: "Md. Naimur Rahman",
        department: "CSE",
        batch: "8th Batch",
        designation: "Senior Software Engineer",
        company: "Google",
        location: "Singapore",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Naimur",
        linkedin: "https://linkedin.com",
        email: "naimur@example.com"
    },
    {
        id: 2,
        name: "Sarah Ahmed",
        department: "BBA",
        batch: "10th Batch",
        designation: "HR Manager",
        company: "Unilever Bangladesh",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/e2e8f0/475569?text=Sarah",
        linkedin: "https://linkedin.com",
        email: "sarah@example.com"
    },
    {
        id: 3,
        name: "Tanvir Hasan",
        department: "CSE",
        batch: "12th Batch",
        designation: "Full Stack Developer",
        company: "Brain Station 23",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Tanvir",
        linkedin: "https://linkedin.com",
        email: "tanvir@example.com"
    },
    {
        id: 4,
        name: "Farhana Islam",
        department: "MBA",
        batch: "5th Batch",
        designation: "Assistant Vice President",
        company: "City Bank Ltd.",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/e2e8f0/475569?text=Farhana",
        linkedin: "https://linkedin.com",
        email: "farhana@example.com"
    },
    {
        id: 5,
        name: "Rafiqul Islam",
        department: "THM",
        batch: "9th Batch",
        designation: "General Manager",
        company: "Radisson Blu",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Rafiqul",
        linkedin: "https://linkedin.com",
        email: "rafiqul@example.com"
    },
    {
        id: 6,
        name: "Sumaiya Akter",
        department: "CSE",
        batch: "14th Batch",
        designation: "SQA Engineer",
        company: "Enosis Solutions",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/e2e8f0/475569?text=Sumaiya",
        linkedin: "https://linkedin.com",
        email: "sumaiya@example.com"
    },
    {
        id: 7,
        name: "Abdullah Al Mamun",
        department: "BBA",
        batch: "11th Batch",
        designation: "Supply Chain Manager",
        company: "BAT Bangladesh",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Abdullah",
        linkedin: "https://linkedin.com",
        email: "mamun@example.com"
    },
    {
        id: 8,
        name: "Tasnim Jarrett",
        department: "THM",
        batch: "13th Batch",
        designation: "Operations Manager",
        company: "InterContinental Dhaka",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/e2e8f0/475569?text=Tasnim",
        linkedin: "https://linkedin.com",
        email: "tasnim@example.com"
    },
    {
        id: 9,
        name: "Shafiqur Rahman",
        department: "CSE",
        batch: "7th Batch",
        designation: "CTO",
        company: "TechValley",
        location: "New York, USA",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Shafiqur",
        linkedin: "https://linkedin.com",
        email: "shafiqur@example.com"
    },
    {
        id: 10,
        name: "Nusrat Jahan",
        department: "MBA",
        batch: "8th Batch",
        designation: "Brand Manager",
        company: "Grameenphone",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/e2e8f0/475569?text=Nusrat",
        linkedin: "https://linkedin.com",
        email: "nusrat@example.com"
    },
    {
        id: 11,
        name: "Kamrul Hasan",
        department: "CSE",
        batch: "15th Batch",
        designation: "Software Engineer",
        company: "Pathao",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Kamrul",
        linkedin: "https://linkedin.com",
        email: "kamrul@example.com"
    },
    {
        id: 12,
        name: "Ayesha Siddiqua",
        department: "BBA",
        batch: "14th Batch",
        designation: "Financial Analyst",
        company: "IDLC Finance",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/e2e8f0/475569?text=Ayesha",
        linkedin: "https://linkedin.com",
        email: "ayesha@example.com"
    },
    {
        id: 13,
        name: "Imran Hossain",
        department: "CSE",
        batch: "9th Batch",
        designation: "DevOps Engineer",
        company: "AWS",
        location: "Dublin, Ireland",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Imran",
        linkedin: "https://linkedin.com",
        email: "imran@example.com"
    },
    {
        id: 14,
        name: "Sadia Afrin",
        department: "THM",
        batch: "11th Batch",
        designation: "Guest Relations Manager",
        company: "Westin Dhaka",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/e2e8f0/475569?text=Sadia",
        linkedin: "https://linkedin.com",
        email: "sadia@example.com"
    },
    {
        id: 15,
        name: "Monirul Islam",
        department: "MBA",
        batch: "6th Batch",
        designation: "Marketing Director",
        company: "Robi Axiata Ltd",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Monirul",
        linkedin: "https://linkedin.com",
        email: "monirul@example.com"
    },
    {
        id: 16,
        name: "Fahim Ahmed",
        department: "CSE",
        batch: "16th Batch",
        designation: "Frontend Developer",
        company: "Chaldal",
        location: "Dhaka, Bangladesh",
        image: "https://placehold.co/400x400/1e293b/cbd5e1?text=Fahim",
        linkedin: "https://linkedin.com",
        email: "fahim@example.com"
    }
];
